### PR TITLE
Fixed an error in minified version for "treeRightClick" directive

### PR DESCRIPTION
**Pull request by meet-asite**
Fixed below error:

` Error: [$injector:unpr] Unknown provider: eProvider <- e <- treeRightClickDirective `

### CODE REVIEW

**Comment by trakinos** [comment]
Nice! Have been strugling with this issue. Waiting for update!

**Comment by meet-asite** [comment]
Hi @yoavaa 
Could you please merge this PR?

**Comment by meet-asite** [comment]
Thank you @yoavaa for merging the PR. Could you please let us know when are we going to release?

**Comment by OskarPersson** [comment]
@yoavaa @wix any updates here?

**Pull request merged**
