### PR TITLE
Custom icons in leaf

### PR DESCRIPTION
**Pull request by lautarobock**
Can create custom icons (images) in leafs.

**Use**
```
$scope.options = {
    customIcon: function (node) {
       //return imageUrl based on node values
        return process(node);
    }
};
```

### CODE REVIEW

**Comment by yoavaa** [comment]
there is no need for such a pool request.
When building folders and files, the tree icons are just for the expand and collapse (what we have in windows as the [+] and [-] icons).

The actual folder and file icons are rendered using the item template, not the support of the tree control, allowing you the developer using the tree control to select in your template what icons to use.

**Comment by lautarobock** [comment]
Sorry, but I didn't see the "item template". 

Just can customize in transclude the whole node but not the icon. This is in `treeitem` directive.
But icons is above of this, Here

```
'<i class="tree-branch-head" ng-class="iBranchClass()" ng-click="selectNodeHead(node)"></i>' +
                            '<i class="tree-leaf-head '+classIfDefined($scope.options.injectClasses.iLeaf, false)+'"></i>' +
```

And I don't know how to override this template.

Thanks

**Comment by yoavaa** [comment]
I have added a docs section to explain - see here - http://wix.github.io/angular-tree-control/#file-style

Basically, you include an ng-switch inside the tree label template.

**Comment by LTroya** [comment]
Is there a way to override the caret on that example? I am looking for a way to override it

**Pull request closed without merging**
