### PR TITLE
https://github.com/wix/angular-tree-control/issues/214

### PR DESCRIPTION
**Pull request by destromas1**

### CODE REVIEW

**Comment by yoavaa** [comment]
1. The tests are failing, so we cannot merge. 
2. you changed the interface of external API functions like defaultEquality - and I'd rather not do that as it is a breaking change. Adding the $scope parameter as the first parameter of the function is a breaking change.

**Comment by destromas1** [comment]
@yoavaa Yes I saw the Test is failing after my change . Then I reverted my code and tried to run test but Test was failing then also . Can u plz check on the master branch that Test passes or fails ?

**Comment by yoavaa** [comment]
it is working in master.
Just checked.

The reason it fails is because the equality function used to accept (a,b)
and now accepts (scope,a,b). If the default quality will get (a,b,scope)
instead of (scope,a,b) it will be backward compatible.

**Comment by destromas1** [comment]
@yoavaa  I will make the changes and push!

**Comment by destromas1** [comment]
@yoavaa Test passes now . Please merge ! Thanks!

**Pull request merged**
