### PR TITLE
Adding double click support

### PR DESCRIPTION
**Pull request by seiyria**
`on-dbl-click` is the attribute name.

How's this look? I have a lot more features I want to make but I figured I'd start simple.

### CODE REVIEW

**Comment by cgalvan** [comment]
Any updates on this one?  This would be a super helpful feature.

**Comment by yoavaa** [comment]
will have to find the time to work on this. It is missing some features (the $ variables in the event handler and docs) and will have to go over the tests as well. Will try to do so soon

**Comment by paambaati** [comment]
+1 for this. This is a great and sorely-missed feature.

**Comment by yoavaa** [comment]
I do not object merging this one, but the pool request does not have docs and it is missing some features (the $ variables in the event handler)

**Comment by paambaati** [comment]
@yoavaa I actually don't mind submitting a fixed PR if you can tell me a little bit more about the `$` variables you're looking for.

**Comment by yoavaa** [comment]
have a look at the [events](http://wix.github.io/angular-tree-control/#events) part in the docs. All the event handlers get a set of variables that can be used by the event handler. 

This is how it is done for the on-selection event:
https://github.com/wix/angular-tree-control/blob/master/angular-tree-control.js#L217-L220

and for node toggle:
https://github.com/wix/angular-tree-control/blob/master/angular-tree-control.js#L168-L171

**Pull request closed without merging**
