### PR TITLE
ContextMenu and RightClick done properly.

### PR DESCRIPTION
**Pull request by stueynz**
The context menu functionality from [pull request 96](https://github.com/wix/angular-tree-control/pull/96) was a little too simplistic.  Building context menu from a model was all very well & good, but we needed a few things:
- Make it work without jQuery - just jqLite
- Sub Context Menus
- The ability to do all that angular goodness to the menu (& sub menu) - directives, bindings, to adjust the menu based on context.
-  Make sure the context will fit when you're at the bottom / right of the window - and maybe put sub-menu on left rather than right.

Oh and context-menu-id will work as a directive all on it's own of course.

### CODE REVIEW

**Comment by boiawang** [comment]
good

**Comment by ramseyfeng** [comment]
When will this pull request be merged?

**Comment by yoavaa** [comment]
There are too many conflicts to simply merge. Can you help resolve all the conflicts?
I'd love to merge if I can, as this seems like a great feature. However, I do not have the time to do so.

**Comment by ramseyfeng** [comment]
Maybe the author @stueynz can help to resolve the conflicts.

**Comment by stueynz** [comment]
Gosh it's been a while.... I'll drag it up to master in the coming week.

**Comment by stueynz** [comment]
Ok this Pull Request should now be easy for WIX to include in the original project.

**Comment by ramseyfeng** [comment]
@stueynz Thanks! Will this be merged? @yoavaa

**Comment by yoavaa** [comment]
Hay, just tried to merge. It appears that sortByExpression does not work for some reason.
Can you check?

**Comment by yoavaa** [comment]
Merged!!!

**Comment by ramseyfeng** [comment]
Thanks! :+1:

**Pull request merged**
