### PR TITLE
External template

### PR DESCRIPTION
**Pull request by nikolay-lesko**
With these changes you are now able to specify tree control template via external file or $templateCache.

Now you are able to specify structure of whole control, not only of the label.

The default template is still preserved when there was no template specified.

### CODE REVIEW

**Comment by yoavaa** [comment]
Great work, will really like to merge this PR. I have some minor but important comments - please fix those and I will merge (or will find the time sometime in the next month to do so myself).

**Comment by nikolay-lesko** [comment]
Hello.

I changed so now you can specify template url per control instance or globally for all instances during run/config step.
Also I added demo to the index.html.

Please review and merge, or let me know if you have some comments.

**Comment by nikolay-lesko** [comment]
Hello.

Could you please provide comments on these changes.
I'm really waiting for this merge to be applied.
Thanks in advance.

**Comment by yoavaa** [comment]
I have added a test to check the functionality. merging

**Comment by nikolay-lesko** [comment]
Thank you.

**Pull request merged**
